env:
- REPORT_CARD_GITHUB_API_TOKEN=$$report_card_github_api_token
image: clever/drone-go:1.5
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  catapult:
    url: $$catapult_url
    application: "who-is-who"
  docker:
    docker_version: 1.7.1
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/who-is-who
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: haproxy-headers-test
script:
- pip install -q git+git://github.com/Clever/report-card.git && GITHUB_API_TOKEN=$REPORT_CARD_GITHUB_API_TOKEN report-card --publish
- make test
- make build
