image: clever/drone-go:1.7
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: $$app_name
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/$$app_name
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
  npm:
    token: $$npm_token
    folder: gen-js/
    when:
      branch: master
env:
  - APP_NAME=$$app_name
script:
- make install_deps
- make test
- make build

