rules:
  indent:
    - warn
    - 2
  quotes:
    - error
    - double
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-console:
    - warn
env:
  es6: true
  browser: false
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2020
