swagger: '2.0'
info:
  title: who-is-who
  description: Discover aliases from one piece of your organization's digital identity
  version: 0.1.0
  x-npm-package: # Put the name of the npm package you're publishing here - remember to scope with @clever/package-name if it's private
schemes:
  - http
produces:
  - application/json
paths:
  /_health:
    get:
      operationId: healthCheck
      description: Checks if the service is healthy
      responses:
        200:
          description: OK response

