version: 2
jobs:
  build:
    working_directory: ~/Clever/who-is-who
    docker:
    # It's awkward to find a way to simultaneously have the correct version of node and of Go
    # Since this repo is primarly a node repo, we'll use our standard node image and install a version of go
    # as a pre-built binary
    - image: circleci/node:14-stretch
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - setup_remote_docker
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run:
        name: Install Go 1.16
        command: |-
          wget https://golang.org/dl/go1.16.8.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.16.8.linux-amd64.tar.gz
    - run:
        command: |-
          sed -i.bak s/\${npm_auth_token}/$NPM_TOKEN/ .npmrc_docker
          mv .npmrc_docker .npmrc
        name: Set up .npmrc
    - run: npm install
    - run:
        name: Run tests
        command: |
          export PATH=$PATH:/usr/local/go/bin
          make test
    - run: npm prune --production
    - run: $HOME/ci-scripts/circleci/docker-publish $DOCKER_USER $DOCKER_PASS "$DOCKER_EMAIL" $DOCKER_ORG
    - run: $HOME/ci-scripts/circleci/catapult-publish $CATAPULT_URL $CATAPULT_USER $CATAPULT_PASS $APP_NAME
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME clever-dev no-confirm-deploy; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS $APP_NAME production no-confirm-deploy; fi;
